### ISSUE TITLE
Determine which website builder to use

### ISSUE THREAD

**Issue by imAlan** [SeedToSTEM/Website#5]
Take a look at the features, maintainability and costs then determine which is better for our use case.

weebly: https://www.weebly.com/

wix:  https://www.wix.com/

googles sites: https://gsuite.google.com/learning-center/products/sites/get-started/#!/

**Comment by amy-lei** [comment]
@imAlan Does this mean we'll buy a domain name and not have to use seedtostem.wix.com kinds of urls?

**Comment by amy-lei** [comment]
@imAlan I think Wix would be our best option. 

Google sites lacks A LOT of the features that Wix and Weebly offer. It's fairly simple, but I think we wouldn't be able to implement everything from our wireframe. 
Weebly doesn't offer a way to create our own domain (assuming that's what we want); we would have to use domain.com or another site to set it up. Plus, I've dipped my feet into Weebly and Wix before, so this might just be a preference thing.

**Comment by imAlan** [comment]
@lei-01 good research! how about wordpress? consider the pricing as well. wordpress is $4 if we upgrade and wix is $5 if we upgrade but still has the ads. let me know you thoughts?

**Comment by amy-lei** [comment]
@imAlan 
I played around with Wordpress for a bit.
The price for Wordpress is really tempting!! But it seems like we're stuck with whatever layout we choose. I was able to change the fonts and colors but not actually move things around. 

I feel like the extra $1 for more customization is well worth it but the ads for Wix are a little off-putting...

**Comment by imAlan** [comment]
@lei-01 I agree, let's go with Wix! 👍good research analysis! You can close this issue.
